### ISSUE TITLE
Infinite loop in get_module_by_name

### ISSUE THREAD

**Issue by davemcincork** [hasherezade/masm_shc#3]
https://github.com/hasherezade/masm_shc/blob/05c71497225d132cbfa17a6f80ca61a711b8bf67/demos/peb_lookup.h#L83

if ``curr_module->BaseAddress`` is non-null and ``curr_module->BaseDllName.Buffer`` is null, the while loop goes infinite. Reason is that the advance to the next list item is skipped on continue. Suggest turning the ``while`` loop into a ``for`` loop, i.e.

```C++
for (
    PLDR_DATA_TABLE_ENTRY curr_module = Flink;
    curr_module && curr_module->BaseAddress;
    curr_module = (PLDR_DATA_TABLE_ENTRY)curr_module->InLoadOrderModuleList.Flink) {
```

**Comment by hasherezade** [comment]
Thank you, fixed!
